version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - cd project-front
      - npm install 
      - npm run-script build
      - ls
artifacts: 
  files:
    - '**/*'
  base-directory: 'project-front/dist/my-first-app'
